### ISSUE TITLE
Will move to TypeScript?

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/IxJS#1]
Do you have any plan to move to TypeScript?

I think there are some benefits
- for generic collections
- to uniform with https://github.com/ReactiveX/RxJS

**Comment by mattpodwysocki** [comment]
@saneyuki Not yet, as this is more to prove out the design of Iterables and AsyncIterables

**Comment by marcinnajder** [comment]
Hi, I did my own implementation https://github.com/marcinnajder/powerseq What do yo think ? :) 

I am a huge fan of LINQ/RxJS from many many years. I work with JS/TS 4 years now, ES6 + TS + iterators + generators (natively on node) + VS code + RxJS5 approach to writing operators   is such a amazing combination.

**Comment by mattpodwysocki** [comment]
@saneyuki closing as it is now written in TypeScript
