### ISSUE TITLE
Test harness

### ISSUE THREAD

**Issue by zenparsing** [ReactiveX/IxJS#2]
@mattpodwysocki There currently isn't any testing harness.  Can we add one?  I have no preferences on which one, although it should support promises.

**Comment by mattpodwysocki** [comment]
@zenparsing either Mocha or Tape is good enough for me.

**Comment by saneyuki** [comment]
We're [allowing to failure the test](https://github.com/ReactiveX/IxJS/blob/f0c7f9a8d093c1d423666a67d5d19feb06a512b4/.travis.yml#L19) (introduced by #16). We need to enable it when we resolve this.

**Comment by trxcllnt** [comment]
@saneyuki @mattpodwysocki @zenparsing what work is left to be done here? do we need anything besides `npm test` exiting with a non-zero error code?

**Comment by saneyuki** [comment]
@trxcllnt 

We need to remove [this allowing failure section](https://github.com/ReactiveX/IxJS/blob/6cbe2fadb9661644328b6112f84e71cc2be5f763/.travis.yml#L22-L24) when we finish to pass `npm test` with no error code.

**Comment by mattpodwysocki** [comment]
Closing as per stale issue
