### ISSUE TITLE
Some operators are not exposed as lettables

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/IxJS#213]
**IxJS version:** 2.3.4

Whilst `import { filter } from 'ix/iterable/pipe/filter';` works, `import { orderBy } from 'ix/iterable/pipe/orderby';` does not (module does not exist).

I can see the lettable operator defined in the source code (https://github.com/ReactiveX/IxJS/blob/master/src/iterable/orderby.ts), but this is not in the released npm package: https://unpkg.com/ix@2.3.4/iterable/pipe/

**Comment by trxcllnt** [comment]
Ah yeah we might have added that after the most recent publish. I’ll review today and republish a new version with the latest!
