### ISSUE TITLE
IxJS not compatible with typescript 2.7

### ISSUE THREAD

**Issue by patsissons** [ReactiveX/IxJS#214]
**IxJS version:**
`2.3.4`

**Code to reproduce:**
this is a type declaration error, so any usage of `tsc` with the current version of `ix` will fail.

**Expected behavior:**
no compilation errors

**Actual behavior:**
example output (using the webpack `at-loader`)
```
ERROR in [at-loader] ./node_modules/ix/add/asynciterable-operators/concat.ts:63:10
    TS2556: Expected 1-6 arguments, but got 1 or more.

ERROR in [at-loader] ./node_modules/ix/add/asynciterable-operators/merge.ts:63:10
    TS2556: Expected 1-6 arguments, but got 1 or more.

ERROR in [at-loader] ./node_modules/ix/add/iterable-operators/concat.ts:54:10
    TS2556: Expected 1-6 arguments, but got 1 or more.
```

**Additional information:**
There are some missing exports on the above 3 mentioned files that declare the _catch all_ function signatures (exports without implementation). I'm not completely certain what changed from 2.6.x to 2.7.x, but there was some change that now requires these additional exports when overloading a function signature. I will be publishing a PR for this fix shortly.

**Comment by patsissons** [comment]
Until #215 is merged, there is a work around by performing some unconventional augmentations.

```ts
import { IterableX } from 'ix/iterable/iterablex';
import { AsyncIterableX } from 'ix/asynciterable/asynciterablex';

declare module 'ix/iterable/concat' {
  // @ts-ignore: static function overload augmentation
  function concat<T>(source: IterableX<T>, ...args: Iterable<T>[]): IterableX<T>;
}

declare module 'ix/asynciterable/concat' {
  // @ts-ignore: static function overload augmentation
  function concat<T>(source: AsyncIterableX<T>, ...args: AsyncIterable<T>[]): AsyncIterableX<T>;
}

declare module 'ix/asynciterable/merge' {
  // @ts-ignore: static function overload augmentation
  function merge<T>(source: AsyncIterableX<T>, ...args: AsyncIterable<T>[]): AsyncIterableX<T>;
}
```

**Comment by trxcllnt** [comment]
thanks @patsissons, I was worried we might see some issues with 2.7. Will validate the fix (and maybe fix CI) later tonight.
