### ISSUE TITLE
Failed type inference using `from` static method with Rx.Observable

### ISSUE THREAD

**Issue by KonanMentor** [ReactiveX/IxJS#236]
**IxJS version:** 2.3.5

**RxJS version:** 5.5.11

**Code to reproduce:**

```typescript
import * as Ix from 'ix';
import * as Rx from 'rxjs';

const source = Rx.Observable.of(1, 2, 3);
const iterable = Ix.AsyncIterable.from(source); // Ix.AsyncIterable<{}>
```

**Expected behavior:**

```typescript
...
const iterable = Ix.AsyncIterable.from(source); // Ix.AsyncIterable<number>
```

**Actual behavior:**

```typescript
...
const iterable = Ix.AsyncIterable.from(source); // Ix.AsyncIterable<{}>
```

**Additional information:**

It seems that is happens due to the behaviour that is described [here](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#type-inference-in-conditional-types).

> When inferring from a type with multiple call signatures (such as the type of an overloaded function), inferences are made from the last signature (which, presumably, is the most permissive catch-all case). It is not possible to perform overload resolution based on a list of argument types.

If we reorder the `subscribe` method signatures in `rxjs` definitions, then `number` type is inferred.

```diff
diff --git a/src/Observable.ts b/src/Observable.ts
index 8aa37227..24c6eb10 100644
--- a/src/Observable.ts
+++ b/src/Observable.ts
@@ -73,8 +73,8 @@ export class Observable<T> implements Subscribable<T> {
     return observable;
   }
 
-  subscribe(observer?: PartialObserver<T>): Subscription;
   subscribe(next?: (value: T) => void, error?: (error: any) => void, complete?: () => void): Subscription;
+  subscribe(observer?: PartialObserver<T>): Subscription;
   /**
    * Invokes an execution of an Observable and registers Observer handlers for notifications it will emit.
    *
```

**Comment by trxcllnt** [comment]
Seems reasonable. I'll add it to the backlog

**Comment by trxcllnt** [comment]
Resolved by https://github.com/ReactiveX/IxJS/pull/259
