### ISSUE TITLE
API docs missing

### ISSUE THREAD

**Issue by slikts** [ReactiveX/IxJS#240]
I'm not sure if I'm being obtuse, but where are the API docs? Even the default tsdoc output would help.

**Comment by slikts** [comment]
I tried running the esdoc npm script after building, but that only seemed to copy sources into .html files. Running typedoc worked, however; the result can be seen here: https://slikts.github.io/IxJS/

**Comment by trxcllnt** [comment]
@slikts thanks, this looks great! @mattpodwysocki what do you think?

**Comment by slikts** [comment]
I've actually found it simpler to directly use the source as a reference. The typedoc results might be better than nothing, but they're rather noisy and chaotic. esdoc might be better, but I'm not familiar enough with either this or it to make it work. documentation.js is nice, but it unfortunately [doesn't support TS][doc] (yet?).

[doc]: https://github.com/documentationjs/documentation/issues/282

**Comment by mpodwysocki** [comment]
@trxcllnt agreed! Looks great to me

**Comment by ShawnTalbert** [comment]
Isn't there API docs somewhere? I thought the main `readme.md` had a link to docs once upon a time? Or if not, it's pretty a common pattern to have API docs linked from the readme so that it show sup here on GitHub or npm.

**Comment by BrutalSimplicity** [comment]
Am I missing something or has this library remained only partially documented for the last 2 years?

The link above is ok, but it would be nice if there were more complete examples of the more esoteric functions.

**Comment by trxcllnt** [comment]
Docs now published at https://reactivex.io/IxJS/ :tada:
