### ISSUE TITLE
Failing CI

### ISSUE THREAD

**Issue by DanielRuf** [ReactiveX/IxJS#263]
https://ci.appveyor.com/project/mattpodwysocki/ixjs/builds/21615478

**Expected behavior:**
CI should succeed.

**Actual behavior:**
CI fails.

**Additional information:**

**Comment by trxcllnt** [comment]
Yeah Appveyor is flaky, because the `takeUntil` and `debounce` tests are non-deterministic. @mattpodwysocki and I have discussed hardening these operators, but the solution probably involves a implementing a deterministic test scheduler which we haven't gotten to.

**Comment by trxcllnt** [comment]
Yeah, we do use Travis too: https://travis-ci.org/ReactiveX/IxJS/. I didn't know Travis does windows, I haven't been a windows guy for over a decade. I think @mattpodwysocki did the appveyor setup initially, Matt you got any feeling about this?

**Comment by DanielRuf** [comment]
We already use it in a few projects like foundation-sites: https://blog.travis-ci.com/2018-10-11-windows-early-release
