### ISSUE TITLE
AsyncIterableX.pipe()  is missing in published package

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/IxJS#265]
**IxJS version:** 2.5.1 (latest)

`.pipe()` is missing in the latest version of Ix. It is present on master

https://unpkg.com/ix@2.5.1/asynciterable/asynciterablex.d.ts
https://github.com/ReactiveX/IxJS/blob/master/src/asynciterable/asynciterablex.ts

**Comment by trxcllnt** [comment]
Ah yes, the type definition was moved to the `ix.node` file when we added stream support to pipe. I was intending to add the corresponding definition to `ix.dom` when we add whatwg DOM stream support there.
