### ISSUE TITLE
Typescript distribution

### ISSUE THREAD

**Issue by WorldMaker** [ReactiveX/IxJS#27]
**IxJS version:** 2.0.1

Under the new publishing regime with its breakdown by target and module type, and since I am already using Typescript myself, I would like to see a `@reactivex/ix-ts` that is simply a package of the Typescript source files without cruft and loadable directly as is. This would allow me to use my project's existing `tsconfig.json` target and module settings. This would make it easier to be more nimble in my own builds/packs, for example. It also further reduces the possibility space where TS may be able to load the types for the library, but not, for example, webpack find the JS modules and/or vice versa.

**Comment by trxcllnt** [comment]
@WorldMaker ah, right! will update the build and report back here when we have that module published. thanks!

**Comment by trxcllnt** [comment]
@WorldMaker closing as resolved, as now we publish [`@reactivex/ix-ts`](https://www.npmjs.com/package/@reactivex/ix-ts)
