### ISSUE TITLE
from() should be exported like other static operators from ix/iterable/index, not just sit on class

### ISSUE THREAD

**Issue by felixfbecker** [ReactiveX/IxJS#271]
I often use both Ix and Rx in one project, which means to avoid nameclashes I need to import Ix like this:
```ts
import * as ix from 'ix/iterable/index'
import * as ixop from 'ix/iterable/pipe/index'
import * as rx from 'rxjs'
import * as rxop from 'rxjs/operators'
```

This allows me to e.g. reference `ix.concat()`, but I always have to write `ix.IterableX.from()`, which is annoying. Rx on the other hand allows me to do `rx.from()`.

**Comment by trxcllnt** [comment]
Yeah, that's a pain. @mattpodwysocki does have this in-progress branch that moves everything around so it's structured more like Rx: https://github.com/ReactiveX/IxJS/pull/264. I think it's mostly done, but we've been having trouble getting vscode to recognize the tsconfig path mapping in the Ix tests
