### ISSUE TITLE
String should be iterable

### ISSUE THREAD

**Issue by proteriax** [ReactiveX/IxJS#276]
**IxJS version:** 2.5.3

**Code to reproduce:**
```ts
Ix.Iterable.from("Hello World")
```

**Expected behavior:**
Returns an `Iterable<string>` of each character.

**Actual behavior:**
```ts
throw new TypeError('Input type not supported');
```

**Additional information:**
Culprit is here:
```js
function isIterable(x) {
  return exports.isObject(x) && exports.isFunction(x[Symbol.iterator]);
}
```

**Comment by trxcllnt** [comment]
ah yes. @mattpodwysocki any reason we're casting against to an object in this check? @glixlur in the meantime, you can pass the string's Iterator to `Iterable.from()`.
