### ISSUE TITLE
timeout does not call return on source iterator

### ISSUE THREAD

**Issue by backbone87** [ReactiveX/IxJS#280]
https://github.com/ReactiveX/IxJS/blob/master/src/asynciterable/timeout.ts#L31

**IxJS version:** 2.5.3

**Code to reproduce:**
```ts
const ee = new EventEmitter();
try {
  const bar = await fromEvent(ee, 'foo').finally(() => void console.log('finally')).timeout(1000).take(1).toArray();
} catch (e) {
  console.log(e instanceof TimeoutError);
}
```

**Expected behavior:**
timeout returns the source iterator and therefore `finally` getting logged

**Actual behavior:**
timeout does not return the source iterator and therefore `finally` never gets logged

**Additional information:**
wrapping the whole while loop into a `try ... finally` works:
```ts
const it = this._source[Symbol.asyncIterator]();
try {
  while (1) {
    // ...
  }
} finally {
  await returnAsyncIterator(it);
}
```

also the timeout function is missing from `AsyncIterableX.prototype`

**Comment by backbone87** [comment]
seems finally itself has the same problem. do i get something wrong about the concept or are the intermediate iterables responsible for returning the source iterables?

**Comment by trxcllnt** [comment]
Got this implemented in the regular builds, but there seems to be a bug in closure-compiler: https://github.com/google/closure-compiler/issues/3971
