### ISSUE TITLE
Transpilation error when using Ix with typescript 3.7.3

### ISSUE THREAD

**Issue by jonatannyberg** [ReactiveX/IxJS#286]
**IxJS version:** 2.5.3

**Code to reproduce:**
`import { Iterable } from 'ix'` (for example)

Transpile with typescript 3.7.2 or 3.7.3 using tsconfig.json generated with `tsc --init`.

**Expected behavior:** 
For this to transpile successfully using typescript 3.7.2 and 3.7.3.

**Actual behavior:**
Produces two transpilation errors with typescript 3.7.2 or 3.7.3:
```
node_modules/ix/Ix.d.ts:5:10 - error TS2440: Import declaration conflicts with local declaration of 'GroupedIterable'.

5 import { GroupedIterable } from './iterable/groupby';
           ~~~~~~~~~~~~~~~

node_modules/ix/Ix.d.ts:6:10 - error TS2440: Import declaration conflicts with local declaration of 'GroupedAsyncIterable'.

6 import { GroupedAsyncIterable } from './asynciterable/groupby';
           ~~~~~~~~~~~~~~~~~~~~
 ```

**Additional information:**
The issue seems to be that the imported and exported names of `GroupedIterable` and `GroupedAsyncIterable` respectively are the same in Ix.d.ts. 

Renaming the imports with `as` in Ix.d.ts and using the renamed imports to create the exported declarations of `GroupedIterable` and `GroupedAsyncIterable` resolves the errors.

**Comment by nancyyhong** [comment]
I've just created a PR that should fix this

https://github.com/ReactiveX/IxJS/pull/287

**Comment by michaelsbradleyjr** [comment]
Since #287, this issue should be closed.
