### ISSUE TITLE
some operator should support omitted comparer

### ISSUE THREAD

**Issue by patsissons** [ReactiveX/IxJS#29]
**IxJS version:** 2.0.1

**Code to reproduce:** `Iterable.of([1]).some()`

**Expected behavior:** returns true

**Actual behavior:** expected 1 params, but got 0

**Additional information:** 

pretty simple fix, just change
`if (comparer(item, i++)) { return true; }`
to
`if (!comparer || comparer(item, i++)) { return true; }`

**Comment by mattpodwysocki** [comment]
@patsissons disagree here since `isEmpty` should suffice for checking if the collection has any values.  I'd rather stick with the ECMA standard for `Array.prototype.some`.

**Comment by patsissons** [comment]
yea that's fine with me, I guess i didn't really think of using the negation of `isEmpty` instead.
