### ISSUE TITLE
Operators documentation

### ISSUE THREAD

**Issue by arturohernandez10** [ReactiveX/IxJS#306]
I will find a way to use this library. The main reason is that I want the flexibility that it will give to my code. But one major hurdle that I can see is the lack of documentation on the operators. I understand that this operators are modeled after RxJs and other libraries. But it would be nice to have at least a list of functions, and if there is parity with Rxjs. Maybe a few links to online tutorials.  I could volunteer if you need the help.

**Comment by conartist6** [comment]
If you're interested, `iter-tools` has similar functionality with [full documentation](https://github.com/iter-tools/iter-tools/blob/trunk/API.md).
