### ISSUE TITLE
No ordered iterable type is exported

### ISSUE THREAD

**Issue by patsissons** [ReactiveX/IxJS#31]
**IxJS version:** 2.0.1

**Code to reproduce:** `let source: OrderedIterable<number> = Iterable.from([1]).orderBy(x => x)`

**Expected behavior:** No type definition errors on `OrderedIterable`

**Actual behavior:** `no exported member OrderedIterable<T>`

**Additional information:**

This is useful if we ever need to define an unassigned ordered iterable variable. It's also convenient if we want to re-assign a variable via dynamic chaining (i.e. orderby, if condition thenby).

This ought to be a relatively simple fix. The simple version is to simply export `OrderedIterableBaseX as OrderedIterable` in the api surface. A slightly more involved fix is to create an actual `OrderedIterable` interface and export that (though i doubt it provides any benefits over the simple fix).

**Comment by patsissons** [comment]
I'm not sure how strictly important this is as the work-around is relatively simple and the people that may actually make use of this is possibly quite small.

**Comment by mattpodwysocki** [comment]
@patsissons can you verify now?

**Comment by patsissons** [comment]
I believe that is nearly identical to what I had stubbed in during testing.
