### ISSUE TITLE
What happened to the function signature on reduce (and scan)?

### ISSUE THREAD

**Issue by tvedtorama** [ReactiveX/IxJS#311]
I tried to upgrade to v4, but all my reduce-related code failed to compile.  Turns out the signature for reduce is no longer the same as for array.reduce, with an options-object instead of the two arguments for callback and seed.

This will not compute for me, as it requires huge rewrites.  Also, functions requiring an object with a reduce function, will no longer work with IterableX-instances, only arrays.

Why is this change introduced?

**Comment by trxcllnt** [comment]
@tvedtorama IIRC AsyncIterable's `scan` and `reduce` signatures changed to accommodate an optional [AbortSignal addition](https://github.com/ReactiveX/IxJS/commit/6e848f16116a21cb650e441826c30893fd73c32b#diff-b0d96d7a20e8f6af1f9193b49fb43dba437c621c3bdb0d560e3223ecc5ae9199), so I imagine @mattpodwysocki updated Iterable's signatures to maintain symmetry.

That said, it'd be good if Iterable's signature to still matched the Array built-in's.

**Comment by tvedtorama** [comment]
Ok,

thank you - that explains the change.  I still think this might be a major issue with many upgraders, though.  Perhaps it could be possible to support both function signatures?

**Comment by trxcllnt** [comment]
@tvedtorama Yeah, we should be able to do that easily. I'll open a PR.

**Comment by trxcllnt** [comment]
@tvedtorama just published `ix@4.1.0` with this fix. Thanks!
