### ISSUE TITLE
docs(readme): `Array#extras` link is defunct

### ISSUE THREAD

**Issue by jajaperson** [ReactiveX/IxJS#319]
The link in README to <https://devblogs.microsoft.com/blogs.msdn.com/13> is defunct, I am not sure where this is meant to go.

**Comment by trxcllnt** [comment]
@mattpodwysocki looks like blogs.msdn.com removed the Array Extras archive link: http://blogs.msdn.com/b/ie/archive/2010/12/13/ecmascript-5-part-2-array-extras.aspx

Is there another one we can link to?

**Comment by trxcllnt** [comment]
Fixed in https://github.com/ReactiveX/IxJS/pull/343
