### ISSUE TITLE
Update docs to include some getting started details with tsconfig

### ISSUE THREAD

**Issue by patsissons** [ReactiveX/IxJS#32]
**IxJS version:** 2.0.1

**Additional information:**

When i got started with `ix` while targetting `es5` I did not realize that I would need to add some extra libs to the typescript compiler to get things compiling (I had thought I was missing some `@types` for shims). by adding `esnext.asynciterable` to `lib` I was able to bring in the necessary type definitions to squelch the compiler errors. While it didn't take me too long to figure this out, anyone not very familiar with the typescript compilation process might struggle with this.  You could also maybe point them to your own source controlled `tsconfig.base.json`, but i think the only absolutely required lib is `esnext.asynciterable` (which itself brings in symbol and iterable).

**Comment by trxcllnt** [comment]
Going to mark this resolved as now the section on @angular/cli integration [mentions `esnext.asynciterable`](https://github.com/ReactiveX/IxJS/commit/91c36a246c3d6760fdfffd6e04ad68d0b48a1901#diff-0730bb7c2e8f9ea2438b52e419dd86c9R41). Thanks for the heads up!
