### ISSUE TITLE
Typescript >= 4.3.2

### ISSUE THREAD

**Issue by gewoonjerry** [ReactiveX/IxJS#331]
IxJS does not compile anymore when using typescript >= 4.2.3 (which is required for Angular 12)

Compiler returns the following errors:
node_modules/ix/asynciterable/todomstream.d.ts:36:55 - error TS2304: Cannot find name 'PipeOptions'.
node_modules/ix/iterable/todomstream.d.ts:19:22 - error TS2304: Cannot find name 'PipeOptions'.

**IxJS version:** 4.4.1

**Additional information:**
Typescript version: >= 4.2.3

**Comment by trxcllnt** [comment]
Ah yes, because they removed those types. Shit.
