### ISSUE TITLE
When will be the next release? 

### ISSUE THREAD

**Issue by eunohshure** [ReactiveX/IxJS#368]
Hi all, 
I'm wondering when you're planning to promote the next release. I've been waiting for bug fixes since the last release. 
Please release a new version if possible. 

Thanks in advance.

**Comment by trxcllnt** [comment]
Releasing v6 tonight, once https://github.com/ReactiveX/IxJS/pull/363 is merged.

**Comment by trxcllnt** [comment]
[v6.0.0](https://github.com/ReactiveX/IxJS/releases/tag/v6.0.0) is published!
