### ISSUE TITLE
flatMap operator has no resultSelector parameter

### ISSUE THREAD

**Issue by patsissons** [ReactiveX/IxJS#38]
**IxJS version:** `2.0.1`

**Additional information:**

`flatMap` will always emit the inner result, which is sometimes not desired. we can use an optional `resultSelector` parameter to inject our own result projection using both the inner and outer values.

**Comment by patsissons** [comment]
I am working on a PR for this right now.

**Comment by mattpodwysocki** [comment]
@patsissons 'flatMap' as implemented works as expected and conforms to the [ES FlatMap proposal](https://github.com/tc39/proposal-flatMap) This deviates from RxJS and previous versions of IxJS, but I want this implementation to conform to the spec.

**Comment by patsissons** [comment]
I see. can you please post a work around? i cannot think of any way to accomplish a flatMap projection..

**Comment by mattpodwysocki** [comment]
@patsissons sure! It's as simple as 'source.flatMap(x => selector(x).map(y => { return { x, y }; }))'

**Comment by patsissons** [comment]
SMH, can't believe I was so oblivious haha, sorry for the disturbance.
