### ISSUE TITLE
Asynciterable forEachAsync recurse function should return promise?

### ISSUE THREAD

**Issue by christyharagan** [ReactiveX/IxJS#4]
Hey there,

Just looking through the code and noticed the following entry inside `asynciterable.js`:

``` js
  var recurse = function () {
    p = e.next().then(function (result) {
      if (!result.done) {
        cb(result.value, i++);
        recurse();
      } else {
        Promise.resolve();
      }
    });
   return p;
  };
```

Should this instead be?:

``` js
  var recurse = function () {
    p = e.next().then(function (result) {
      if (!result.done) {
        cb(result.value, i++);
        return recurse();
      } else {
        return Promise.resolve();
      }
    });
    return p;
  };
```

I.e.: Shouldn't the function return a promise? This ensures the promise doesn't resolve on the first element.

**Comment by zenparsing** [comment]
@christyharagan

Honestly, I didn't even look at that function when I got AsyncIterable working, so I have no idea!  I'll take a look later on today though.

Thanks!

**Comment by christyharagan** [comment]
Thinking about it some more, I actually think my version won't work either. I think this is the right version (looking at the whole method):

```js
AsyncIterable.prototype.forEachAsync = function (fn, thisArg) {
  var cb = bindCallback(fn, thisArg, 2);
  var i = 0, e = this[$asyncIterator$]();
  return new Promise(function(resolve, reject){
    var recurse = function () {
      e.next().then(function (result) {
        if (!result.done) {
          cb(result.value, i++);
          recurse();
        } else {
          resolve();
        }
      }).catch(function(e){
        reject(e);
      });
    };

    recurse();
  });
};

```

**Comment by zenparsing** [comment]
That looks about right.  My take is here: https://github.com/ReactiveX/IxJS/pull/5

(Also, I pulled out the thisArg thing for now.)

**Comment by christyharagan** [comment]
Ah yes, much cleaner :)

**Comment by mattpodwysocki** [comment]
Closing as per new design
