### ISSUE TITLE
Support user defined type guards in filter predicates

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/IxJS#44]
**IxJS version:**
2.1.0

**Code to reproduce:**
``` ts
// no error, good!
// TypeScript's Array typings support user defined type guards in the filter predicate
const xs: number[] = ['foo', 1].filter((x): x is number => x instanceof Number);

// unexpected error
const xs2: Ix.Iterable<number> = Ix.Iterable
    .from(['foo', 1])
    .filter((x): x is number => x instanceof Number);
```

**Comment by ichpuchtli** [comment]
wow I didn't know that that's awesome.

**Comment by trxcllnt** [comment]
that is sick -- how would we go about supporting this?

**Comment by trxcllnt** [comment]
@OliverJAsh 🎉 thanks!

**Comment by OliverJAsh** [comment]
@trxcllnt Using 2.1.4, the example above still seems to generate an error. Any ideas?

**Comment by trxcllnt** [comment]
@OliverJAsh I don't think they made it in the 2.1.4 release, will circle back with @mattpodwysocki and do another release soon

**Comment by trxcllnt** [comment]
@OliverJAsh just pushed this out in 2.2.0. I also wanna call out [this breaking change](https://github.com/ReactiveX/IxJS/pull/73) to `zip`

**Comment by OliverJAsh** [comment]
I'm using 2.2.0 and the example above still seems to generate an error. Any ideas? @trxcllnt

```
❯ grep version node_modules/ix/package.json
  "version": "2.2.0",
```

![image](https://user-images.githubusercontent.com/921609/31587840-9c00dec2-b1e0-11e7-9cd3-79eef48750d8.png)

**Comment by trxcllnt** [comment]
@OliverJAsh oh you're right, looks like I forgot to extend the [generic type](https://github.com/ReactiveX/IxJS/pull/56/files#diff-aa90e45f494e48ae697cd001aad3eca6R3):

```ts
// this
export type booleanPredicate<T> =
{ (value: T, index: number): boolean } |
{ (value: T, index: number): value is T };
// should be
export type booleanPredicate<T> =
{ (value: T, index: number): boolean } |
{ <S extends T>(value: T, index: number): value is S };
```

Although there's still the issue that `1 instanceof Number` evaluates to `false`, so the runtime behavior won't be what you expect even though TS gives the OK. I ran into that in the [type guards test](https://github.com/ReactiveX/IxJS/pull/56/files#diff-06eb3cbe8530913fe5c16ace0f113a08R38)

**Comment by OliverJAsh** [comment]
Thanks for the fix @trxcllnt. I'll give it another go once it's released.

> There's still the issue that 1 instanceof Number evaluates to false

I've updated the example in the original post now.

**Comment by OliverJAsh** [comment]
@trxcllnt Thanks for fixing this! My original example works, however this doesn't:

``` ts
// no error, good!
const xs2: Ix.Iterable<number> = Ix.Iterable
    .from(['foo', 1])
    .filter((x): x is number => typeof x === 'number')

// no error, good!
const xs2b: Ix.Iterable<number> = xs2.map(x => x);

// unexpected error, bad!
const xs3: Ix.Iterable<number> = Ix.Iterable
    .from(['foo', 1])
    .filter((x): x is number => typeof x === 'number')
    .map(x => x)
```

Any ideas what is causing this?

**Comment by OliverJAsh** [comment]
I opened a separate issue to track the above https://github.com/ReactiveX/IxJS/issues/162
