### ISSUE TITLE
Lettable operators

### ISSUE THREAD

**Issue by saneyuki** [ReactiveX/IxJS#46]
On rxjs side, [they're implementing lettable operators](https://github.com/ReactiveX/rxjs/blob/master/doc/lettable-operators.md) to make it more friendly with tree shaking.
I think it's better that we also consider to accept the way.

**Comment by saneyuki** [comment]
relate: https://github.com/ReactiveX/IxJS/pull/75

**Comment by mattpodwysocki** [comment]
Closed as per #75
