### ISSUE TITLE
create a really nice tree-shakable ES module, with flow function

### ISSUE THREAD

**Issue by graingert** [ReactiveX/IxJS#52]
```js
// ES
import * as ix from 'ix/es';

const fn = ix.flow(
  ix.from,
  ix.filter(x => x % 2 === 0),
  ix.map(x => x * x),
);

const results = fn([1, 2, 3]);

for (let item of results) {
  console.log(`Next: ${item}`);
}
```

**Comment by trxcllnt** [comment]
@graingert we support importing operators individually at the moment, but we also have work planned to export pipe-friendly variants of each operator.

You can also use the [`ix/iterable/__modules`](https://github.com/ReactiveX/IxJS/blob/master/src/iterable/__modules.ts) default export, which I _think_ can be tree-shook automatically (if not, we can change this back to the `export *` form). We only use this module internally so the operator names survive minification so they're [accessible](https://github.com/ReactiveX/IxJS/blob/master/spec/asynciterable-operators/count-spec.ts#L3) to the tests ([setup here](https://github.com/ReactiveX/IxJS/blob/master/spec/Ix.ts#L27)), but they're also available in the `Ix.internal` UMD bundles.

We also recommend using [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) to help decompose large explicit operator imports. Hope this helps!

**Comment by graingert** [comment]
@trxcllnt the export default is not tree-shakeable.

**Comment by trxcllnt** [comment]
@graingert no problem then, we can change that easily enough.

It's a default export b/c closure-compiler doesn't work with `export *`, but considering we don't run the raw ES2015 through CC yet, we can change it and figure that out when CC is ready.

**Comment by graingert** [comment]
@trxcllnt I'd like a true .mjs module available in the package.

**Comment by trxcllnt** [comment]
> @graingert a true .mjs module

do you mind clarifying what you mean? we are publishing the es2015/ESModules compilation target as `.mjs` in the main ix package:

<img width="769" alt="screen shot 2017-10-04 at 12 27 57 pm" src="https://user-images.githubusercontent.com/178183/31195626-ca9d4674-a8ff-11e7-82ea-f0f725434fc1.png">

**Comment by graingert** [comment]
As apposed to one with a single default export, as in __module

**Comment by trxcllnt** [comment]
yeah one [like this](https://github.com/ReactiveX/IxJS/blob/a05e0852171de6ec5ce452d1b5c371bcc0056b79/src/iterable/__modules.ts), right?

**Comment by graingert** [comment]
Yes exactly like that

**Comment by trxcllnt** [comment]
yeah I said we can do that again

**Comment by graingert** [comment]
Nice, didn't know it was there

**Comment by graingert** [comment]
Should I open a new issue for curried, data-last function

**Comment by trxcllnt** [comment]
@graingert nah we already got #23 and #46, and it's planned. would be happy to review a PR if you want to do the manual work of adding all the new pipe-aware impls (and if so, hmu cuz we have thoughts about how to make it less painful), but otherwise it'll happen when we have time.
