### ISSUE TITLE
Full re-write... Happy to contribute

### ISSUE THREAD

**Issue by christyharagan** [ReactiveX/IxJS#6]
Hi guys,

I have just committed a full re-write of IxJS in TypeScript, complete with several new operators and tests. I followed the RxJS pattern of things (including extending base types, and npm scripts).

Please see here: [https://github.com/christyharagan/IxJS](https://github.com/christyharagan/IxJS)

I haven't published any packages yet as I'd like to make the offer of migrating re-write code to this repository.

It works for CJS, AMD, and ES6, has full test coverage (although I'm sure the tests themselves may need beefing up), and linting.

Let me know what you guys think.

I'd also like to propose the generator\* extensions for async-iterators to the TypeScript guys, although if the base spec is likely to change a lot, then I'll hold off.

Let me know what you think...

**Comment by ichpuchtli** [comment]
@mattpodwysocki yes please. I don't mind helping as well.

**Comment by mattpodwysocki** [comment]
@christyharagan @ichpuchtli all are welcome to contribute here now that we have everything up and running again with the lights back on.
