### ISSUE TITLE
default comparer function should be more accurate

### ISSUE THREAD

**Issue by patsissons** [ReactiveX/IxJS#81]
**IxJS version:** 
`2.1.4`

**Code to reproduce:**
```ts
import { Iterable } from 'ix';

// actually false (count is 1)
const shouldBeTrue = Iterable.of('foo', 'bar').distinct().count() === 2;
```

**Expected behavior:**
`shouldBeTrue` should be `true`

**Actual behavior:**
`shouldBeTrue` is be `false`

**Additional information:**
the default comparer should have some more comparator fallbacks to better handle strings and objects. I have been using a custom comparer for a while now, it may be a bit overkill but it works really well with whatever you throw at it.

```ts
export interface Comparable<T> {
  compareTo(other: T): number;
}

export function isComparable<T>(obj: any): obj is Comparable<T> {
  return (<Comparable<T>>obj).compareTo instanceof Function;
}

export function isString(value: any): value is string {
  return typeof(value) === 'string' || value instanceof String;
}

export function DefaultComparer(a: any, b: any) {
  if (a === b || (a == null && b == null)) {
    // both are null or the same, so equality is zero
    return 0;
  }
  else if (a == null || b == null) {
    // only one is null, non-null takes higher value
    return a == null ? -1 : 1;
  }
  else if (typeof a === 'object' || typeof b === 'object') {
    // if either side is an object then we have failed referencial equality (first compare)
    return -1;
  }
  else if (isComparable(a)) {
    // implements Comparable
    return a.compareTo(b);
  }
  else if (String.isString(a) && String.isString(b)) {
    // native string comparison
    return a.localeCompare(b);
  }
  else {
    // fallback on a basic equality check
    const c: number | undefined = a - b;

    // it's possible that our basic check failed, so default to zero
    return (c == null || isNaN(c)) ? 0 : c;
  }
}
```

**EDIT**: forgot to include the object comparer.

**Comment by trxcllnt** [comment]
I'd be down for having a way to configuring the defaultCompare. I'd be wary of us hard-coding anything fancy esp. wrt `localCompare`, I've had to debug major perf issues w/ that in (probably now outdated versions of) node before.

Regardless it looks like the [`defaultCompare`](https://github.com/ReactiveX/IxJS/blob/master/src/internal/comparer.ts#L6) we have now is straight up busted, as it falls back to `isNaN` if the values aren't equal:

```ts
export function comparer(a: any, b: any) {
  return (a === 0 && b === 0) || (a === b || (isNaN(a) && isNaN(b)));
}
```

So in this case `isNaN('foo') && isNaN('bar') === true`. @mattpodwysocki thoughts?

**Comment by patsissons** [comment]
yea that snippet is just what i am using currently, but not necessarily a suggestion for a replacement. I think your idea to inject a custom default comparer function is a great idea.

**Comment by mattpodwysocki** [comment]
@patsissons closed by https://github.com/ReactiveX/IxJS/commit/c6a67ebe517e25451b9f7071d1924d2f36b4b42f
