### ISSUE TITLE
Cancellation?

### ISSUE THREAD

**Issue by OliverJAsh** [ReactiveX/IxJS#9]
Do you have any ideas for how an async iterable, transformed using IxJS, can be cancelled by the consumer?

Obviously, async iterables use Promises which are not cancellable.

I'm really starting to wish async iterables used something that did support cancellation, such as [`Task`s](https://github.com/rpominov/fun-task). Then the user could receive an `unsubscribe` function, just like in RxJS with the `Observable` type.

**Comment by rafaelkallis** [comment]
The iterator interface allow the consumer to cancel the iteration using the `return` function.

```
interface AsyncIterator<T> {
    next(value?: any): Promise<IteratorResult<T>>;
    return?(value?: any): Promise<IteratorResult<T>>;
    throw?(e?: any): Promise<IteratorResult<T>>;
}
```

Extra reading: https://gist.github.com/dherman/11057861

**Comment by mattpodwysocki** [comment]
@OliverJAsh yes, @rafaelkallis is correct here that `return` has the `cancel` semantics here with things that happen when an iteration `for await of` ends either naturally or there is a `break`
